### ISSUE TITLE
Creating fake pages programmatically

### ISSUE THREAD

**Issue by mileyvirus** [sformisano/jetrouter#10]
Do you have any clue on how to programmatically create a 'fake page' or a 'virtual page' for JetRouter routes?

I'm building a dynamic route that queries an external API so I'm like
 
```
 use JetRouter\Router;
 
 $config = [];
 
 $r = Router::create($config);

 $r->get('movie/{movie}', 'get_movie', function($movie){
 	include ( get_stylesheet_directory() . '/movie.php' );
 });
```
 

and so far so good. In `movie.php` I have a page template which calls `cptemplates_template_content();` which is a wrapper around WordPress' `the_content()` that applies a WPBakery Page Builder template to whatever the API call returned and then renders `the_content()`.

But WordPress doesn’t recognize what I output as a page because it isn’t.

So when I go like `if URL, WP->REQUEST matches 'movie/{movie}' return the Custom Page Template` it doesn't work because the plugin doesn't see a page and the browser shows whatever is in `movie.php` which is a themed empty page with header and footer but no content because I called `include ( get_stylesheet_directory() . '/movie.php' );` earlier.

One solution would be to create real pages with the same slug I would query on the external API which obviously is a hassle. I see on the internet that when this situation happens you're supposed to create a 'fake' or 'virtual' dummy page which [is very well described here on StackOverflow](https://stackoverflow.com/questions/17960649/wordpress-plugin-generating-virtual-pages-and-using-theme-template).

**Comment by sformisano** [comment]
Hey @mileyvirus this isn't a use case I ever stumbled upon to be honest, but yes, it sounds like one would have to hack with hooks/filters or even just the global query object early in the process so that the subsequent operations are tricked into believing this is a request to a real existing page.

In fact, the whole point of this router was to completely skip anything WordPress and plugins want to do and just display whatever was in the route callback.

I also think with the WordPress API themes and how to work with them will likely become less relevant over time.

You could write an idempotent function that creates the pages if they do not exist when a route is created. You wouldn't have to create them to wp-admin if you did it that way. The same goes if movies is a CPT and movie is a CPT post.

**Comment by sformisano** [comment]
This is a very simple example of how you could create pages programmatically, it has nothing to do with `jetrouter` but it may solve the problem you are having if I understand it correctly. You can group calls to this function, loop over an array of pages you want to create etc.

This function also has a check to make sure it does not run on front-end, but I would make sure to only run it when you activate the theme. If you then need to re-trigger if, for example if you added a page, you could disable and re-enable the theme to run it again.

```
function programmatically_create_page($title, $slug, $post_type = 'page', $setup_template = false) {
  // only run this when an admin page is seen, to reduce queries on front-end
  if( ! is_admin() ){
    return;
  }

  // Initialize the page ID to -1. This indicates no action has been taken.
  $post_id = -1;

  // Setup the author, slug, and title for the post
  $author_id = 1;

  // If the page doesn't already exist, then create it
  if( null == get_page_by_title( $title, 'OBJECT', $post_type ) ) {

    // Set the post ID so that we know the post was created successfully
    $post_id = wp_insert_post(
      array(
        'comment_status'  =>  'closed',
        'ping_status'     =>  'closed',
        'post_author'     =>  $author_id,
        'post_name'       =>  $slug,
        'post_title'      =>  $title,
        'post_status'     =>  'publish',
        'post_type'       =>  $post_type
      )
    );

    if( $setup_template ){
      update_post_meta($post_id, '_wp_page_template', 'template-' . $slug . '.php');
    }

  // Otherwise, we'll stop
  }
  else {
    // Arbitrarily use -2 to indicate that the page with the title already exists
    $post_id = -2;
  }
}
```

**Comment by mileyvirus** [comment]
Ciao Salvatore, vorrei ringraziarti tantissimo per esserti ritagliato un po' di tempo per leggere e comprendere il mio problema e aver proposto una soluzione. Sei stato davvero gentilissimo!

For the sake of possible future readers I'll keep this in English while doing my best to convey my situation – even if poorly.

> In fact, the whole point of this router was to completely skip anything WordPress and plugins want to do and just display whatever was in the route callback.

I have to say that I write a lot of spaghetti code because I'm actually just a designer trying to hack together something that fits my specific needs so I could actually be wrong about my whole approach with this.

I read your function and I don't think that's my case cause `wp_insert_post` writes the pages to the database and that's not what I'd need, even if it could be an viable automation if I chose the approach of creating a page for each movie.

If at any point you feel like this isn't in the scope of your free open source time tell me and I'll close the issue and mail you for a quote!

I'm actually having the same use case as [this guy on SO](https://stackoverflow.com/questions/17960649/wordpress-plugin-generating-virtual-pages-and-using-theme-template), my page has to query an external API so it doesn't need to have a WordPress page created in WP's DB for each and every movie The Movie Database (TMDb) contains. It only needs to be editable in WPBakery Page Builder hence the other plugin [Custom Page Templates](custompagetemplates.com).

With [Custom Page Templates](custompagetemplates.com) I'm able to visually build a frontend template that gets applied to whatever one wishes like custom post types, 404 pages or custom stuff: matching a JetRouter route which I do with this clumsy way:

```
add_filter( 'cptemplates/get_current_request_name', function( $request_type ) {
  $url_pieces = explode('/', $_SERVER['REQUEST_URI']);
  if (in_array('movies', $url_pieces)) $request_type = 'movie';
  return $request_type;
} );
```

My JetRouter route defines however I imagine is prettier for users and SEO purposes.

```
 $r->get('movie/{movie}', 'get_movie', function($movie){
 	include ( get_stylesheet_directory() . '/movie.php' );
 });
```

Now `movie.php` makes an API call to The Movie Database (TMDb) with one query: the `{movie}` which is in slug case and that works fine. I print some template with Twig.

The thing is: Custom Page Templates doesn't recognize that whatever is in `site.com/movies/toy-story` is a WP Page so it doesn't return the WPBakery Page Builder template because it's not a page as you said because JetRouter is an external layer.

That takes me out of the WordPress realm so I can't use some of that sweet Yoast SEO plugin on that movie page or even that WPBakery Page Builder template.

I'm positive by what you said that the fake page or virtual page approach is the best one here for maintaining some theme/page builder compatibility. I'm just missing how to do it. 🤔

By writing this I'm actually realizing that maybe JetRouter doesn't actually meet my need in this particular situation but I love its syntax for creating routes and being stubborn. 😂

**Comment by sformisano** [comment]
Hey @mileyvirus yeah like I said I think you're trying to do literally the opposite thing I built JetRouter for. I'm unable to look into this any further for the time being, but your use case is interesting and I may add a solution for it in the future. If I find the time to do it anytime soon I'll reopen this issue and mention you ;)

Cheers,
Salvatore
