### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by whatthefork** [sformisano/jetrouter#9]
An error occurs if the route's function or class method doesn't exist before adding a route. Taht condition generates a fatal error before the jetrouter can throw its own exception: 

**Fatal error: Uncaught Error: Using $this when not in object context in /var/www/jetrouter/src/RouteParser.php:78**

I was calling addRoute like this, but had not yet written the get_dashboard class method into the code.

`$router->addRoute( 'GET', 'dashboard', 'dashboard_route', __CLASS__ . '::get_dashboard' );`

**Comment by sformisano** [comment]
Hey @whatthefork I haven't had time to properly maintain `jetrouter` and saw you forked it, was it to fix this issue?

**Comment by restless-khai** [comment]
Hey! Got the same issue, will proposed a fix.

**Comment by restless-khai** [comment]
#17 Here's a fix.
